BoxLayout:
    orientation: 'vertical'

    Button:
        text: 'Clear'
        on_press: app.handle_clear()
    TextInput:
        id: input_name
        text: ''
        font_size: 48
        multiline: False
    Button:
        text: 'Greet'
        # the following line specifies the function in the app class to call when the button is pressed
        on_press: app.handle_greet(input_name.text)
    Label:
    
        id: output_label
        font_size: 48
        color: (1, 1, 0, 1)
